services:
   postgres:
      image: postgres:16
      env_file:
         - .env
      environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_DB: ${POSTGRES_DB}
      ports:
         - '5432:5432'
      volumes:
         - ${POSTGRES_VOLUME_NAME}:/var/lib/postgresql/data
volumes:
   ${POSTGRES_VOLUME_NAME}:
